name: Run Test Suite

on:
  schedule:
    - cron: '0 6 * * *'
  
  workflow_dispatch:
    inputs:
      test:
        description: 'Select test to run: all, ymbi_set, test_set'
        required: true
        default: all
        type: choice
        options:
          - all
          - ymbi_set
          - test_set

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test_type: [all, ymbi_set, ymbi_set]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          if [[ "${{ matrix.test_type }}" == "all" ]]; then
            echo "Running all tests"
            pytest  src/tests/test_stock_symbol_scrape.py
          elif [[ "${{ matrix.test_type }}" == "ymbi_set" ]]; then
            echo "Running Google Finance Data Not In Test Data Set"
            pytest src/tests/test_stock_symbol_scrape.py -m ymbi_set
          elif [[ "${{ matrix.test_type }}" == "test_set" ]]; then
            echo "Running Test Data Not In Google Finance Data Set"
            pytest src/tests/test_stock_symbol_scrape.py -m test_set
          fi
        env:
          TEST_TYPE: ${{ matrix.test_type }}
